# Generated by Django 6.0.2 on 2026-02-18 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(help_text='BPM')),
                ('systolic_bp', models.IntegerField(help_text='mmHg')),
                ('spo2', models.IntegerField(help_text='%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('respiratory_rate', models.IntegerField(help_text='Breaths/min')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, help_text='List of chronic conditions')),
                ('er_visits', models.IntegerField(default=0, help_text='Number of ER visits in last 6 months')),
                ('wbc_flag', models.BooleanField(default=False, verbose_name='Elevated WBC')),
                ('creatinine_flag', models.BooleanField(default=False, verbose_name='Elevated Creatinine')),
                ('crp_flag', models.BooleanField(default=False, verbose_name='Elevated CRP')),
                ('risk_score', models.IntegerField(default=0, editable=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('risk_before', models.CharField(max_length=10)),
                ('risk_after', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='risk_monitor.patient')),
            ],
        ),
    ]
