# Generated by Django 6.0.2 on 2026-02-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Clinical Notes'),
        ),
    ]
