# Generated by Django 6.0.2 on 2026-02-18 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0002_patient_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
