# Generated by Django 6.0.2 on 2026-02-18 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0003_alter_patient_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
