# Generated by Django 6.0 on 2026-02-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0004_alter_patient_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Risk trace reasoning'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='score_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='score_before',
            field=models.IntegerField(default=0),
        ),
    ]
