# Generated by Django 6.0 on 2026-02-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0005_auditlog_reason_auditlog_score_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
