# Generated by Django 6.0 on 2026-02-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_monitor', '0006_alter_patient_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='batch_id',
            field=models.UUIDField(blank=True, help_text='Groups multiple field changes from one update', null=True),
        ),
    ]
